### ISSUE TITLE
Update code 

### ISSUE THREAD

**Issue by greenpdx** [ChrisPWill/easy_password#2]
The code has not been updated for years,  a pull request is avaiable

**Comment by ChrisPWill** [comment]
Hey mate thanks for the heads up, I've merged the PR and after making another little update I'll release a new version.

**Comment by ChrisPWill** [comment]
Alrighty, I've updated the library to the latest versions of the underlying libraries. Thanks for the ping, I'll try and keep on top of this going forward.
